using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using QUANLYKHACHSAN.Object;
using QUANLYKHACHSAN.BUS;

namespace QUANLYKHACHSAN.PresentationLayers
{
    public partial class frmKhachHang : Form
    {
        public frmKhachHang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            LoadData();
        }
        private void LoadData()
        {
            khachhangTableAdapter1.Fill(qlksDataSet1.KHACHHANG);
        }
        private Boolean KiemTra()
        {
            if (txtTenKH.Text == "" || txtCMND.Text == "" || txtSDT.Text == "" || txtEmail.Text == "" || txtDiaChi.Text == "" || txtQuocTich.Text == "" || cbxGioiTinh.Text == "" || dateNgaySinh.Text =="")
            {
                MessageBox.Show("Nhập đầy đủ thông tin", "Thông Báo", MessageBoxButtons.OKCancel, MessageBoxIcon.Warning);
                return false;
            }
            return true;
        }
        private void btnThem_Click(object sender, EventArgs e)
        {
            if (KiemTra())
            {
                try
                {
                    KhachHang kh = new KhachHang();
                    kh.MaKH = KhachHangBUS.XuLyMa();
                    kh.TenKH = txtTenKH.Text;
                    if (cbxGioiTinh.Text == "Nam")
                    {
                        kh.GioiTinh = 1;
                    }
                    else kh.GioiTinh = 0;
                    kh.NgaySinh = dateNgaySinh.DateTime;
                    kh.CMND = txtCMND.Text;
                    kh.Email = txtEmail.Text;
                    kh.QuocTich = txtQuocTich.Text;
                    kh.DiaChi = txtDiaChi.Text;
                    kh.SDT = txtSDT.Text;
                    KhachHangBUS.Insert(kh);
                    LoadData();
                    MessageBox.Show("Thêm khách hàng thành công!", "Thông Báo");

                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
        }

        private void btnNhapLai_Click(object sender, EventArgs e)
        {
            txtMaKH.Reset();
            txtTenKH.Reset();
            txtSDT.Reset();
            txtQuocTich.ResetText();
            txtDiaChi.Reset();
            txtCMND.Reset();
            txtEmail.Reset();
        }

        private void btnXoa_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                
                if(MessageBox.Show("Bạn có chắc chắn muốn xóa?", "Thông Báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question)==DialogResult.Yes)
                {
                    KhachHangBUS.Delete(txtMaKH.Text);
                    LoadData();
                    txtMaKH.Text = "";
                    MessageBox.Show("Xóa Thành Công!");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void btnLuu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (KiemTra())
            {
                try
                {
                    KhachHang kh = new KhachHang();
                    kh.MaKH = txtMaKH.Text;
                    kh.TenKH = txtTenKH.Text;
                    if (cbxGioiTinh.Text == "Nam")
                    {
                        kh.GioiTinh = 1;
                    }
                    else kh.GioiTinh = 0;
                    kh.NgaySinh = dateNgaySinh.DateTime;
                    kh.CMND = txtCMND.Text;
                    kh.Email = txtEmail.Text;
                    kh.QuocTich = txtQuocTich.Text;
                    kh.DiaChi = txtDiaChi.Text;
                    kh.SDT = txtSDT.Text;
                    KhachHangBUS.Update(kh);
                    LoadData();
                    MessageBox.Show("Sửa khách hàng thành công!", "Thông Báo");

                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
        }


        private void gridView1_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            
        }

        private void gridView1_Click(object sender, EventArgs e)
        {
            txtCMND.Text = gridView1.GetFocusedRowCellDisplayText(colCMND);
            txtMaKH.Text = (string)gridView1.GetFocusedRowCellValue(colMaKH);
            txtTenKH.Text = gridView1.GetFocusedRowCellDisplayText(colTenKH);
            txtSDT.Text = gridView1.GetFocusedRowCellDisplayText(colSDT);
            txtQuocTich.Text = gridView1.GetFocusedRowCellDisplayText(colQuocTich);
            txtDiaChi.Text = gridView1.GetFocusedRowCellDisplayText(colDiaChi);
            txtEmail.Text = gridView1.GetFocusedRowCellDisplayText(colEmail);
            dateNgaySinh.Text = gridView1.GetFocusedRowCellDisplayText(colNgaySinh);
            if ((bool)(gridView1.GetFocusedRowCellValue(colGioiTinh)))
            {
                cbxGioiTinh.Text = "Nam";
            }
            else
            {
                cbxGioiTinh.Text = "Nữ";
            }
        }

        private void txtCMND_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (!char.IsDigit(e.KeyChar) && !char.IsControl(e.KeyChar))
            {
                e.Handled = true;
            }
        }

        private void txtSDT_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (!char.IsDigit(e.KeyChar) && !char.IsControl(e.KeyChar))
            {
                e.Handled = true;
            }
        }

    }
}
