using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using QUANLYKHACHSAN.BUS;
using QUANLYKHACHSAN.Object;
using DevExpress.XtraEditors.Controls;
using QUANLYKHACHSAN.Support;

namespace QUANLYKHACHSAN.PresentationLayers
{
    public partial class frmNhanVien : Form
    {
        public frmNhanVien()
        {
            InitializeComponent();
            LoadData();
            
        }
        private void LoadData()
        {
            // This line of code is generated by Data Source Configuration Wizard
            try
            {
                txtMatKhau.Focus();
                nhanvienTableAdapter1.Fill(qlksDataSet1.NHANVIEN);
                chucvuTableAdapter1.Fill(qlksDataSet1.CHUCVU);
                cbxMaCV.Properties.DataSource = qlksDataSet1.CHUCVU;
                cbxMaCV.Properties.DisplayMember = "TenCV";
                cbxMaCV.Properties.ValueMember = "MaCV";

                cbxMaCV.Properties.PopulateColumns();
                cbxMaCV.Properties.Columns.Add(new LookUpColumnInfo("TenCV"));
                cbxMaCV.EditValue = "CV001";
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
            
        }
        private Boolean KiemTra()
        {
            if (txtMatKhau.Text == "" || txtTenNV.Text == "" || txtSDT.Text == "" || txtEmail.Text == "" || txtDiaChi.Text == "" || cbxMaCV.Text == "" || cbxGioiTinh.Text == "" || dateNgaySinh.Text == "")
            {
                MessageBox.Show("Nhập đầy đủ thông tin", "Thông Báo", MessageBoxButtons.OKCancel, MessageBoxIcon.Warning);
                return false;
            }
            if (qlksDataSet1.CHUCVU.FindByMaCV(cbxMaCV.EditValue.ToString())== null)
            {
                MessageBox.Show("Chức vụ không có!", "Thông báo lỗi", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                cbxMaCV.Focus();
                return false;
            }
            if(cbxGioiTinh.Text !="Nam" && cbxGioiTinh.Text !="Nữ")
            {
                MessageBox.Show("Giới tính không có", "Thông báo lỗi", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                cbxGioiTinh.Focus();
                return false;
            }

            return true;
        }

        private void btn_Them_Click(object sender, EventArgs e)
        {
            if (KiemTra())
            {
                try
                {
                    NhanVien nv = new NhanVien();
                    nv.MaNV = NhanVienBUS.XuLyMa();
                    nv.TenNV = txtTenNV.Text;
                    if (cbxGioiTinh.Text == "Nam")
                    {
                        nv.GioiTinh = 1;
                    }
                    else nv.GioiTinh = 0;
                    nv.NgaySinh = dateNgaySinh.DateTime;
                    nv.MatKhau = HamHoTro.MaHoa(txtMatKhau.Text,true);
                    nv.Email = txtEmail.Text;
                    nv.MaCV = (string)cbxMaCV.EditValue;
                    nv.DiaChi = txtDiaChi.Text;
                    nv.SDT = txtSDT.Text;
                    NhanVienBUS.Insert(nv);
                    LoadData();
                    MessageBox.Show("Thêm nhân viên thành công!", "Thông Báo");

                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
        }

        private void btn_NhapLai_Click(object sender, EventArgs e)
        {
            txtMaNV.Reset();
            txtTenNV.Reset();
            txtSDT.Reset();
            cbxMaCV.ResetText();
            txtDiaChi.Reset();
            cbxGioiTinh.Reset();
            txtEmail.Reset();
            dateNgaySinh.Reset();
            txtMatKhau.Reset();
        }

        private void btn_Luu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (KiemTra())
            {
                try
                {
                    NhanVien nv = new NhanVien();
                    nv.MaNV = txtMaNV.Text;
                    nv.TenNV = txtTenNV.Text;
                    if (cbxGioiTinh.Text == "Nam")
                    {
                        nv.GioiTinh = 1;
                    }
                    else nv.GioiTinh = 0;
                    nv.NgaySinh = dateNgaySinh.DateTime;
                    nv.MaCV = (string)cbxMaCV.EditValue;
                    nv.Email = txtEmail.Text;
                    nv.MatKhau = HamHoTro.MaHoa(txtMatKhau.Text, true);
                    nv.DiaChi = txtDiaChi.Text;
                    nv.SDT = txtSDT.Text;
                    NhanVienBUS.Update(nv);
                    LoadData();
                    MessageBox.Show("Sửa Nhân viên thành công!", "Thông Báo");

                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
        }

        private void btnXoa_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {

                if (MessageBox.Show("Bạn có chắc chắn muốn xóa?", "Thông Báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                {
                    NhanVienBUS.Delete(txtMaNV.Text);
                    LoadData();
                    txtMaNV.Text = "";
                    MessageBox.Show("Xóa Thành Công!");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void gridView1_Click(object sender, EventArgs e)
        {

        }

        private void txtSDT_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (!char.IsDigit(e.KeyChar) && !char.IsControl(e.KeyChar))
            {
                e.Handled = true;
            }
        }

        private void btnIn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SaveFileDialog saveFileDialog1 = new SaveFileDialog();
            saveFileDialog1.Filter = "File PDF|*.pdf|Excel|*.xls|Text rtf|*.rtf";
            saveFileDialog1.Title = "Xuất danh sách loại phòng";
            if (saveFileDialog1.ShowDialog() == DialogResult.OK)
            {
                if (saveFileDialog1.FilterIndex == 1)
                    gridView1.ExportToPdf(saveFileDialog1.FileName);
                if (saveFileDialog1.FilterIndex == 2)
                    gridControl1.ExportToXls(saveFileDialog1.FileName);
                if (saveFileDialog1.FilterIndex == 3)
                    gridControl1.ExportToRtf(saveFileDialog1.FileName);
            }
        }

        private void gridView1_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            txtMatKhau.Text = gridView1.GetFocusedRowCellDisplayText(colMatKhau);
            txtMaNV.Text = (string)gridView1.GetFocusedRowCellValue(colMaNV);
            txtTenNV.Text = gridView1.GetFocusedRowCellDisplayText(colTenNV);
            txtSDT.Text = gridView1.GetFocusedRowCellDisplayText(colSDT);
            cbxMaCV.EditValue = gridView1.GetFocusedRowCellValue(colMaCV);
            txtDiaChi.Text = gridView1.GetFocusedRowCellDisplayText(colDiaChi);
            txtEmail.Text = gridView1.GetFocusedRowCellDisplayText(colEmail);
            dateNgaySinh.Text = gridView1.GetFocusedRowCellDisplayText(colNgaySinh);
            if ((bool)(gridView1.GetFocusedRowCellValue(colGioiTinh)))
            {
                cbxGioiTinh.Text = "Nam";
            }
            else cbxGioiTinh.Text = "Nữ";
        }
    }
}
