using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Views.Grid;
using QUANLYKHACHSAN.BUS;
using QUANLYKHACHSAN.Object;
using QUANLYKHACHSAN.Support;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace QUANLYKHACHSAN.PresentationLayers
{
    public partial class frmTimKiemDichVu : Form
    {
        DichVu dv = new DichVu();
        public frmTimKiemDichVu()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            LoadData();
        }

        private void LoadData()
        {
            dichvuTableAdapter1.Fill(qlksDataSet1.DICHVU);
        }

        private int GetRowHandleByColumnValue(GridView view, string ColumnFieldName, object value)
        {
            int result = GridControl.InvalidRowHandle;
            for (int i = 0; i < view.RowCount; i++)
            {
                if (view.GetDataRow(i)[ColumnFieldName].Equals(value))
                    return i;
            }
                
            return result;
        }

        private void btnTimKiem_Click(object sender, EventArgs e)
        {
            switch (cbxTimkiem.Text)
            {
                case "Mã dịch vụ":
                    gridControl1.DataSource = DichVuBUS.SearchBy(HamHoTro.ChuyenKhongDau(txtThongTin.Text), "MaDV");
                    break;
                case "Giá dịch vụ":
                    gridControl1.DataSource = DichVuBUS.SearchBy(HamHoTro.ChuyenKhongDau(txtThongTin.Text), "Gia");
                    break;
                case "Tên dịch vụ":
                    gridControl1.DataSource = DichVuBUS.SearchBy(HamHoTro.ChuyenKhongDau(txtThongTin.Text), "TenDV");
                    break;
                default:
                    MessageBox.Show("Xin chọn loại tìm kiếm");
                    break;
            }
             
        }

        private bool KiemTra()
        {
            if(gridView1.GetFocusedRowCellDisplayText(colGiaDichVu)=="")
            {
                MessageBox.Show("Nhập giá dịch vụ!");
                return false;
            }
            if (gridView1.GetFocusedRowCellDisplayText(colTenDichVu) == "")
            {
                MessageBox.Show("Nhập tên dịch vụ!");
                return false;
            }
            return true;
        }

        private void btnLuu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (KiemTra())
            {
                try
                {
                    dv.MaDV = (string)gridView1.GetFocusedRowCellValue(colMaDV);
                    dv.TenDV = gridView1.GetFocusedRowCellDisplayText(colTenDichVu);
                    dv.MoTa = gridView1.GetFocusedRowCellDisplayText(colMoTa);
                    dv.GiaDV = gridView1.GetFocusedRowCellDisplayText(colGiaDichVu);
                    DichVuBUS.Update(dv);
                    LoadData();
                    MessageBox.Show("Sửa Nhân viên thành công!", "Thông Báo");

                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
        }

        private void btnXoa_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                if (MessageBox.Show("Bạn có chắc chắn muốn xóa?", "Thông Báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                {
                    DichVuBUS.Delete(gridView1.GetFocusedRowCellDisplayText(colMaDV));
                    LoadData();
                    MessageBox.Show("Xóa Thành Công!");
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void btnInDanhSach_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SaveFileDialog saveFileDialog1 = new SaveFileDialog();
            saveFileDialog1.Filter = "File PDF|*.pdf|Excel|*.xls|Text rtf|*.rtf";
            
            if (saveFileDialog1.ShowDialog() == DialogResult.OK)
            {
                if (saveFileDialog1.FilterIndex == 1)
                    gridView1.ExportToPdf(saveFileDialog1.FileName);
                if (saveFileDialog1.FilterIndex == 2)
                    gridControl1.ExportToXls(saveFileDialog1.FileName);
                if (saveFileDialog1.FilterIndex == 3)
                    gridControl1.ExportToRtf(saveFileDialog1.FileName);
            }
        }

        private void txtThongTin_KeyPress(object sender, KeyPressEventArgs e)
        {
            if(cbxTimkiem.Text == "Giá dịch vụ")
            {
                if (!char.IsDigit(e.KeyChar) && !char.IsControl(e.KeyChar))
                {
                    e.Handled = true;
                }
            }
            else
            {
                e.Handled = false;
            }
            
        }
    }
}
