using QUANLYKHACHSAN.BUS;
using QUANLYKHACHSAN.Object;
using QUANLYKHACHSAN.Support;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace QUANLYKHACHSAN.PresentationLayers
{
    public partial class frmTimKiemKhachHang : Form
    {
        public frmTimKiemKhachHang()
        {
            InitializeComponent();
            LoadData();
        }
        private void LoadData()
        {
            // This line of code is generated by Data Source Configuration Wizard
            khachhangTableAdapter1.Fill(qlksDataSet1.KHACHHANG);
        }

        private void btnTimKiem_Click(object sender, EventArgs e)
        {
            try
            {
                if (cbxTimKiem.Text == "Tên Khách Hàng")
                {
                    gridControl1.DataSource = KhachHangBUS.SearchByTenKH(HamHoTro.ChuyenKhongDau(txtThongTin.Text));
                }
                else
                {
                    gridControl1.DataSource = KhachHangBUS.SearchByMaKH(HamHoTro.ChuyenKhongDau(txtThongTin.Text));
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }
        private bool KiemTra()
        {
            if (gridView1.GetFocusedRowCellValue(colMaKH) == null
                || gridView1.GetFocusedRowCellDisplayText(colTenKH) == ""
                || gridView1.GetFocusedRowCellValue(colGioiTinh) == null
                || gridView1.GetFocusedRowCellDisplayText(colNgaySinh) == ""
                || gridView1.GetFocusedRowCellDisplayText(colQuocTich) == ""
                || gridView1.GetFocusedRowCellDisplayText(colEmail) == ""
                || gridView1.GetFocusedRowCellDisplayText(colCMND) == ""
                || gridView1.GetFocusedRowCellDisplayText(colDiaChi) == ""
                || gridView1.GetFocusedRowCellDisplayText(colSDT) == "")
            {
                MessageBox.Show("Không được để trống thông tin");
                return false;
            }
            return true;
        }
        private void btnLuu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (KiemTra())
            {
                try
                {
                    KhachHang kh = new KhachHang();
                    kh.MaKH = (string)gridView1.GetFocusedRowCellValue(colMaKH);
                    kh.TenKH = gridView1.GetFocusedRowCellDisplayText(colTenKH);
                    kh.GioiTinh = (int)gridView1.GetFocusedRowCellValue(colGioiTinh);
                    kh.NgaySinh = Convert.ToDateTime(gridView1.GetFocusedRowCellDisplayText(colNgaySinh));
                    kh.CMND = gridView1.GetFocusedRowCellDisplayText(colCMND);
                    kh.Email = gridView1.GetFocusedRowCellDisplayText(colEmail);
                    kh.QuocTich = gridView1.GetFocusedRowCellDisplayText(colQuocTich);
                    kh.DiaChi = gridView1.GetFocusedRowCellDisplayText(colDiaChi);
                    kh.SDT = gridView1.GetFocusedRowCellDisplayText(colSDT);
                    KhachHangBUS.Update(kh);
                    LoadData();
                    MessageBox.Show("Sửa Nhân viên thành công!", "Thông Báo");

                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
        }

        private void btnInDanhSach_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SaveFileDialog saveFileDialog1 = new SaveFileDialog();
            saveFileDialog1.Filter = "File PDF|*.pdf|Excel|*.xls|Text rtf|*.rtf";
            saveFileDialog1.Title = "Xuất danh sách loại phòng";
            if (saveFileDialog1.ShowDialog() == DialogResult.OK)
            {
                if (saveFileDialog1.FilterIndex == 1)
                    gridView1.ExportToPdf(saveFileDialog1.FileName);
                if (saveFileDialog1.FilterIndex == 2)
                    gridControl1.ExportToXls(saveFileDialog1.FileName);
                if (saveFileDialog1.FilterIndex == 3)
                    gridControl1.ExportToRtf(saveFileDialog1.FileName);
            }
        }
    }
}
